### PR TITLE
Added support for create statements

### PR DESCRIPTION
**Pull request by brian-gates**

### CODE REVIEW

**Comment by brian-gates** [comment]
Have you had a chance to look at this yet? :)

**Comment by Yomguithereal** [comment]
Any chance that this get merged @shesek? Is the library still maintained? If not, can I help in some way?

**Comment by brian-gates** [comment]
@Yomguithereal Pretty sure it's not.  [My fork](https://github.com/brian-gates/cypher-query) has some progress, but ultimately the API has some serious deficiencies for writing anything beyond the most basic Cypher statements.  I'd suggest not using it.

**Comment by Yomguithereal** [comment]
Hello @brian-gates. Could you describe those deficiencies so I can know what could hurt me :smile:?

**Comment by brian-gates** [comment]
@Yomguithereal  WITHs and UNIONs aren't supported.  For example, you can't write this:

```
MATCH (foo)--(bar)
WITH bar
LIMIT 1
MATCH (bar)--(baz)
RETURN baz
```

Pretty much anything beyond the most basic Cypher query starts to fall apart pretty quickly without these features. We're moving away from this library for that very reason.

This library is pretty rudimentary, as was Cypher at the time of writing.  If you look at the source you'll see what I mean, I think.  It's very simple and Cypher these days demands more sophistication.

**Comment by Yomguithereal** [comment]
Sure. But is the library conceptually flawed or is it just lacking query parts necessary to modern cypher? I could easily redevelop the library from scratch to adapt it to modern cypher and with proper tests etc. Just want to know if this would be useful. The sad thing is it would be better to improve this library for two reasons: 1) one more lib on npm means more confusion and 2) I would prefer to respect @shesek's work by not creating a split library which would conceptually be the same (just updated and with some more features).

**Comment by brian-gates** [comment]
The library is conceptually flawed.  If you were to try and write the query example I gave above, you'd write something like this, expecting it to work:

```
cypher()
  .match('(foo)--(bar)')
  .with('bar')
  .limit('1')
  .match('(bar)--(baz)')
  .return('baz')
```

But that results in this query:

```
MATCH (foo)--(bar), (bar)--(baz)
WITH bar
RETURN baz
LIMIT 1
```

Which is not the same at all.  The idea of grouping matches can be appealing in some cases, but I think more often it isn't.

Psuedocoding a new API off the top of my head:

```
cypher()
  .segment()
    .match('(foo)--(bar)')
    .with('bar')
    .limit('1')
  .segment()
    .match('(bar)--(baz)')
    .return('baz')
```

I haven't done much research on the subject.  Other libraries can probably offer some even better solutions.

**Comment by Yomguithereal** [comment]
Ok. I indeed stumbled on this nasty `MATCH` merging thing.  I think this kind of library shouldn't do any magic of the kind. To me, the query should just be built in the order the methods are called. Do you see any case where one would like, for instance, to call the `ORDER BY` method before even making the `MATCH` etc.?

**Comment by Yomguithereal** [comment]
@brian-gates: I added an updated & fixed query builder to the [decypher](https://github.com/Yomguithereal/decypher) library which gathers cypher utilities. Can you tell me whether this would fix your issues if you find some time :smile:?

**Comment by Yomguithereal** [comment]
Updated the lib once more with some helpers @brian-gates.

**Comment by brian-gates** [comment]
I feel like it would be useful to hold onto specific chunks of the query for dynamic modification.  That way it's more explicit when you're grouping matches or are starting a new query segment.  In the API I jotted above, the idea would be that you could hang onto the return of segment() and make calls to it.

```
var q = cypher();

var segment1 = q.segment();
var segment2 = q.segment();

segment1
  .match('(foo)--(bar)')
  .with('bar')
  .limit('1')
;
segment2
  .match('(bar)--(baz)')
  .match('(baz)--(boo)')

q.return('baz');

```

Resulting in something like:

```
MATCH (foo)--(bar)
WITH bar
LIMIT 1
MATCH (bar)--(baz), (baz)--(boo)
RETURN baz
```

The key is to have a good understanding of the cypher syntax and build an API that reflects it.  

```
[MATCH WHERE]
[OPTIONAL MATCH WHERE]
[WITH [ORDER BY] [SKIP] [LIMIT]]
(CREATE [UNIQUE] | MERGE)*
[SET|DELETE|REMOVE|FOREACH]*
[RETURN [ORDER BY] [SKIP] [LIMIT]]
```

Maybe we can have a more implicit segments whenever an appropriate beginning or end is called.  This could be syntactic sugar or it could be syntactic ambiguity, depending how you look at it.

Perhaps something like:

```
query
  .match('(foo)--(bar)') // creates and returns segment[0]
    .match('(bar)--(biz)') // modifies segment[0]
  .with('bar limit 1') // modifies segment[0] and returns query
  .match('(bar)--(baz)') // creates and returns segment[1]
    .match('(baz)--(boo)') // modifies segment[1]
  .return('baz') // modifies and returns query, segment[1] ends with implicit "WITH *"
```

Which would result in:

```
MATCH (foo)--(bar), (bar)--(biz)
WITH bar
MATCH (bar)--(baz), (baz)--(boo)
RETURN BAZ
```

Individual segments could be referenced by keeping the initial return:

```
var query = db.query();

var segment1 = query
  .match('(foo)--(bar)');

segment1
  .with('bar limit 1')

var segment2 = query
  .match('(bar)--(baz)')

query.return('baz')

```

... or segments could also be exposed by an accessor:

```
var query = db.query();

query.match('(foo)--(bar)');

query
  .getSegment(0)
  .with('bar limit 1')

query.match('(bar)--(baz)')

query.return('baz')

```

Again, I would highly suggest researching other libraries that may have solved this and/or popping into the [Public Neo4j Slack Channel](http://neo4j.com/blog/public-neo4j-users-slack-group/) and getting feedback from someone more familiar with the subject than I am.  I'm no expert on the subject, these are just my observations and desires as per my use-cases.

**Comment by brian-gates** [comment]
> Can you tell me whether this would fix your issues if you find some time

Regarding your question specifically, I don't know, but it seems like you could (and should) write a test which covers our example here, then you'll know for sure.

**Comment by shesek** [comment]
Fully agreed; this library is not up-to-date with current the Cypher syntax and does mot properly support queries with multiple UNION/MATCH parts. It definitely requires some work, and was neglected by myself since I'm not an active user anymore.

It should definitely be doable, but does require some changes to cypher-query's internals.

@Yomguithereal no harm taken at all if anyone chooses to fork this! In fact, if anyone is willing to pick that up and bring this library to being functional, I'll gladly give commit access to the repository here and to the package on npm.

**Comment by brian-gates** [comment]
:+1: thanks for your input and support, @shesek :)  Are you not working with Neo4j any longer?

**Comment by Yomguithereal** [comment]
@brian-gates I quite like your segment idea. I think I will implement it soon. However, concerning the query part merging, I am very mitigated. In my current implementation, if you want, for instance, the following:

``` cypher
MATCH (a:Actor), (m:Movie)
```

You'll have to explictly pass an array of strings to the `match` method:

``` js
query.match(['(a:Actor)', '(m:Movie)']);
```

The same way, I don't try to reorder the given statements in what would be the "correct" order (but maybe I should). That is to say if you call the `orderBy` method before the `return` one, then you'll produce an invalid query. I tend to dislike magic in libraries and I haven't chosen yet where the line should be drawn here between what the library should perform "behind your back" and what the user should be allowed to do.

**Comment by Yomguithereal** [comment]
@shesek, I've started to build on your query-builder in the [decypher](https://github.com/Yomguithereal/decypher) library. I can verse the modifications back into your lib if you want (the code base is not the same however, as it is coded in raw JS).

**Pull request closed without merging**
